In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [23]:
A = np.random.randint(1,6,size=(5,5))
A

array([[1, 3, 4, 2, 1],
       [5, 5, 4, 5, 4],
       [3, 1, 4, 2, 1],
       [2, 5, 5, 4, 2],
       [5, 1, 1, 1, 2]])

In [24]:
train_size = 2
X_train = A[:train_size, :]
X_test = A[train_size:, :]

In [25]:
U, s, Vt = np.linalg.svd(A)

In [26]:
U

array([[-0.3310348 ,  0.39401565, -0.26040795, -0.50084899,  0.64537246],
       [-0.65216453, -0.20790351,  0.50200958,  0.4200413 ,  0.32095053],
       [-0.32695334, -0.08687787, -0.80980076,  0.47362608, -0.07385674],
       [-0.53129003,  0.45921332,  0.10456048, -0.20863417, -0.67260161],
       [-0.27555364, -0.76361192, -0.11603412, -0.55214646, -0.15045731]])

In [27]:
np.diag(s)

array([[15.64996758,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  4.73631918,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  2.61372433,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.86701861,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.25003839]])

In [28]:
Vt

array([[-0.44812014, -0.48005749, -0.52221287, -0.44584838, -0.31184305],
       [-0.80352871,  0.33530388,  0.40736101,  0.13681497, -0.23927303],
       [-0.21073835,  0.50724231, -0.7139346 ,  0.25704252,  0.35003016],
       [-0.18196251, -0.60440652, -0.02773152,  0.7601654 ,  0.15153197],
       [-0.27569718, -0.18577973,  0.22556391, -0.37226146,  0.83667155]])

In [29]:
k=2

In [30]:
Uk=U[:,:k]
Vtk=Vt[:k,:]
sk=np.diag(s)[:k,:k]
rpred=np.matmul(np.matmul(Uk,sk),Vtk)

In [31]:
rpred

array([[0.82203648, 3.11276481, 3.46563035, 2.56512141, 1.16903278],
       [5.36490533, 4.5694637 , 4.92876193, 4.41576492, 3.41839199],
       [2.62358232, 2.3183913 , 2.50444217, 2.22502428, 1.69409776],
       [1.97831231, 4.72079994, 5.22803095, 4.00465283, 2.07245829],
       [4.83860594, 0.85750576, 0.77868712, 1.42785898, 2.21017481]])

In [32]:
k=3

In [33]:
Uk1=U[:,:k]
Vtk1=Vt[:k,:]
sk1=np.diag(s)[:k,:k]
rpred1=np.matmul(np.matmul(Uk1,sk1),Vtk1)

In [34]:
rpred1

array([[0.96547229, 2.76751813, 3.95155894, 2.39016937, 0.93079014],
       [5.08839245, 5.23502377, 3.99199787, 4.75303418, 3.87767169],
       [3.06963026, 1.24476428, 4.01555324, 1.68096913, 0.95322535],
       [1.92071915, 4.85942535, 5.03291814, 4.07490057, 2.16811883],
       [4.90251892, 0.7036687 , 0.99521007, 1.34990282, 2.10401724]])

In [35]:
def error(R,Rpred):
  rsme=np.sum(np.sqrt(np.square((R-Rpred))/len(R)))
  return rsme

In [36]:
#RMSE for k=2
print(error(A,rpred))

4.618845479488703


In [37]:
#RMSE for k=3
print(error(A,rpred1))

1.574017919781862


Increasing the latent factors decreases the RMSE

In [38]:
testu=np.array([0,0,2,0,4])

In [39]:
k=3
Uktest=testu[:k]
Vtktest=Vt[:k,:]
sktest=np.diag(s)[:k,:k]
rtest=np.matmul(np.matmul(Uktest,sktest),Vtktest)
rtest

array([-1.10162391,  2.65158315, -3.73205646,  1.34367659,  1.82976468])

In [40]:
error(testu,rtest)

5.8134079832464565

In [41]:
df=pd.read_csv('/content/ratings.csv')
df.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [42]:
# Print Number of users
print(len(df['userId'].unique()))

# Print Number of movies
print(len(df['movieId'].unique()))

# Print Number of ratings
print(len(df['rating'].unique()))

# Print List of unique ratings
print(list(df['rating'].unique()))

610
9724
10
[4.0, 5.0, 3.0, 2.0, 1.0, 4.5, 3.5, 2.5, 0.5, 1.5]


In [43]:
# Get the dataset information
df.describe()

userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [44]:
# Split the data into training and testing sets
train_data, test_data = train_test_split(df, test_size=0.2, random_state=42)

In [45]:
# Create a user-movie matrix
user_movie_matrix = train_data.pivot(index='userId', columns='movieId', values='rating').fillna(0)

In [46]:
from scipy.sparse import coo_matrix
R = coo_matrix(user_movie_matrix.values)

In [47]:
#  Factor matrix shape
M,N=R.shape

# No of Factors - 3
K=3

# using random values of P and Q
P=np.random.rand(M,K)
Q=np.random.rand(K,N)

In [48]:
P

array([[0.3115487 , 0.25052356, 0.73437827],
       [0.50765482, 0.56153404, 0.93521846],
       [0.96993072, 0.53781366, 0.0878795 ],
       ...,
       [0.79747367, 0.15781084, 0.73249109],
       [0.28109814, 0.04413751, 0.56715886],
       [0.7152257 , 0.07358754, 0.74349049]])

In [49]:
Q

array([[0.71257321, 0.5488183 , 0.78491165, ..., 0.59050346, 0.51546688,
        0.45025411],
       [0.89024949, 0.01392073, 0.34684931, ..., 0.69971651, 0.56479111,
        0.01014833],
       [0.33061434, 0.56062289, 0.38481281, ..., 0.88777289, 0.16858568,
        0.04425136]])

In [50]:
from numpy.linalg import norm

def error(R,P,Q,lamda=0.02):
    ratings = R.data
    rows = R.row
    cols = R.col
    e = 0
    for ui in range(len(ratings)):
        rui=ratings[ui]
        u = rows[ui]
        i = cols[ui]
        if rui>0:
            e= e + pow(rui-np.dot(P[u,:],Q[:,i]),2)+\
                lamda*(pow(norm(P[u,:]),2)+pow(norm(Q[:,i]),2))
    return e

In [51]:
rmse = np.sqrt(error(R,P,Q)/len(R.data))
rmse

2.97405284592602

In [52]:
user_means = user_movie_matrix.mean(axis=1)

# Normalize the user-item matrix by subtracting the user's mean rating from their ratings
normalized_user_movie_matrix = user_movie_matrix.sub(user_means, axis=0)
normalized_user_movie_matrix

movieId    1         2         3         4         5         6         7       \
userId                                                                          
1        3.906935 -0.093065  3.906935 -0.093065 -0.093065  3.906935 -0.093065   
2       -0.010909 -0.010909 -0.010909 -0.010909 -0.010909 -0.010909 -0.010909   
3       -0.008906 -0.008906 -0.008906 -0.008906 -0.008906 -0.008906 -0.008906   
4       -0.065568 -0.065568 -0.065568 -0.065568 -0.065568 -0.065568 -0.065568   
5       -0.015474 -0.015474 -0.015474 -0.015474 -0.015474 -0.015474 -0.015474   
...           ...       ...       ...       ...       ...       ...       ...   
606      2.127908 -0.372092 -0.372092 -0.372092 -0.372092 -0.372092  2.127908   
607     -0.060448 -0.060448 -0.060448 -0.060448 -0.060448 -0.060448 -0.060448   
608      2.264333  1.764333  1.764333 -0.235667 -0.235667 -0.235667 -0.235667   
609      2.988645 -0.011355 -0.011355 -0.011355 -0.011355 -0.011355 -0.011355   
610      4.571914 -0.428086 -0.428086 -0.428086 -0.428086 -0.428086 -0.428086   

movieId    8         9         10      ...    191005    193565    193571  \
userId                                 ...                                 
1       -0.093065 -0.093065 -0.093065  ... -0.093065 -0.093065 -0.093065   
2       -0.010909 -0.010909 -0.010909  ... -0.010909 -0.010909 -0.010909   
3       -0.008906 -0.008906 -0.008906  ... -0.008906 -0.008906 -0.008906   
4       -0.065568 -0.065568 -0.065568  ... -0.065568 -0.065568 -0.065568   
5       -0.015474 -0.015474 -0.015474  ... -0.015474 -0.015474 -0.015474   
...           ...       ...       ...  ...       ...       ...       ...   
606     -0.372092 -0.372092 -0.372092  ... -0.372092 -0.372092 -0.372092   
607     -0.060448 -0.060448 -0.060448  ... -0.060448 -0.060448 -0.060448   
608     -0.235667 -0.235667  3.764333  ... -0.235667 -0.235667 -0.235667   
609     -0.011355 -0.011355  3.988645  ... -0.011355 -0.011355 -0.011355   
610     -0.428086 -0.428086 -0.428086  ... -0.428086 -0.428086 -0.428086   

movieId    193573    193579    193581    193583    193585    193587    193609  
userId                                                                         
1       -0.093065 -0.093065 -0.093065 -0.093065 -0.093065 -0.093065 -0.093065  
2       -0.010909 -0.010909 -0.010909 -0.010909 -0.010909 -0.010909 -0.010909  
3       -0.008906 -0.008906 -0.008906 -0.008906 -0.008906 -0.008906 -0.008906  
4       -0.065568 -0.065568 -0.065568 -0.065568 -0.065568 -0.065568 -0.065568  
5       -0.015474 -0.015474 -0.015474 -0.015474 -0.015474 -0.015474 -0.015474  
...           ...       ...       ...       ...       ...       ...       ...  
606     -0.372092 -0.372092 -0.372092 -0.372092 -0.372092 -0.372092 -0.372092  
607     -0.060448 -0.060448 -0.060448 -0.060448 -0.060448 -0.060448 -0.060448  
608     -0.235667 -0.235667 -0.235667 -0.235667 -0.235667 -0.235667 -0.235667  
609     -0.011355 -0.011355 -0.011355 -0.011355 -0.011355 -0.011355 -0.011355  
610     -0.428086 -0.428086 -0.428086 -0.428086 -0.428086 -0.428086 -0.428086  

[610 rows x 8983 columns]

In [53]:
# Apply SVD
U, sigma, Vt = np.linalg.svd(normalized_user_movie_matrix)

In [54]:
k= 3
U_truncated = U[:, :k]
sigma_truncated = np.diag(sigma[:k])
Vt_truncated = Vt[:k, :]

In [55]:
# Reconstruct the user-movie matrix from the reduced dimensions
predicted_ratings = np.dot(np.dot(U_truncated, sigma_truncated), Vt_truncated)
predicted_ratings

array([[ 2.20329653e+00,  1.11321698e+00,  5.82673009e-01, ...,
        -1.38324872e-01, -1.38324872e-01, -1.40354885e-01],
       [ 1.56713909e-01,  1.06537004e-01, -4.08657215e-02, ...,
        -1.08036344e-02, -1.08036344e-02, -7.39961710e-03],
       [ 2.08868655e-02,  9.44303806e-03,  9.72885132e-03, ...,
        -1.19910240e-03, -1.19910240e-03, -1.39962843e-03],
       ...,
       [ 3.55270550e+00,  1.83396409e+00,  5.64987176e-01, ...,
        -2.46134961e-01, -2.46134961e-01, -2.33263574e-01],
       [ 7.95473010e-01,  5.77031331e-01,  2.79390390e-01, ...,
        -5.82376361e-03, -5.82376361e-03, -9.52744494e-03],
       [ 2.43245774e+00,  1.32627467e+00, -5.77936132e-01, ...,
        -2.34511947e-01, -2.34511947e-01, -1.84113599e-01]])

In [56]:
# Convert the predicted ratings back to a DataFrame
predicted_ratings_df = pd.DataFrame(predicted_ratings, columns=user_movie_matrix.columns, index=user_movie_matrix.index)
predicted_ratings_df

movieId    1         2         3         4         5         6         7       \
userId                                                                          
1        2.203297  1.113217  0.582673 -0.064489  0.277179  1.376391  0.512293   
2        0.156714  0.106537 -0.040866 -0.019320 -0.010422 -0.013854 -0.061729   
3        0.020887  0.009443  0.009729  0.000234  0.004331  0.018462  0.009893   
4        0.796657  0.235586  0.239865 -0.068515  0.021476  0.699026  0.208604   
5        0.993048  0.687738  0.358193  0.057878  0.283788  0.526109  0.360726   
...           ...       ...       ...       ...       ...       ...       ...   
606      1.553997  0.057240  0.144692 -0.354966 -0.366380  1.449082 -0.015633   
607      1.537674  0.838650  0.449385 -0.013002  0.252288  0.940486  0.414025   
608      3.552706  1.833964  0.564987 -0.198455  0.261152  1.798822  0.373121   
609      0.795473  0.577031  0.279390  0.052588  0.238002  0.386906  0.281685   
610      2.432458  1.326275 -0.577936 -0.388757 -0.316671  0.178964 -0.913364   

movieId    8         9         10      ...    191005    193565    193571  \
userId                                 ...                                 
1       -0.003337 -0.012294  1.594288  ... -0.140472 -0.138325 -0.139399   
2       -0.011970 -0.022572 -0.013651  ... -0.010052 -0.010804 -0.010428   
3        0.000634  0.001067  0.021823  ... -0.001264 -0.001199 -0.001232   
4       -0.033242 -0.037737  0.502233  ... -0.085879 -0.084051 -0.084965   
5        0.062252  0.076420  1.031284  ... -0.014615 -0.013607 -0.014111   
...           ...       ...       ...  ...       ...       ...       ...   
606     -0.228258 -0.291685  0.094132  ... -0.281578 -0.279200 -0.280389   
607      0.021247  0.022483  1.236230  ... -0.081045 -0.079430 -0.080237   
608     -0.078457 -0.140851  1.927707  ... -0.245877 -0.246135 -0.246006   
609      0.054230  0.065386  0.832385  ... -0.006438 -0.005824 -0.006131   
610     -0.248801 -0.415942 -0.358992  ... -0.224891 -0.234512 -0.229701   

movieId    193573    193579    193581    193583    193585    193587    193609  
userId                                                                         
1       -0.139399 -0.138325 -0.139399 -0.138325 -0.138325 -0.138325 -0.140355  
2       -0.010428 -0.010804 -0.010428 -0.010804 -0.010804 -0.010804 -0.007400  
3       -0.001232 -0.001199 -0.001232 -0.001199 -0.001199 -0.001199 -0.001400  
4       -0.084965 -0.084051 -0.084965 -0.084051 -0.084051 -0.084051 -0.086047  
5       -0.014111 -0.013607 -0.014111 -0.013607 -0.013607 -0.013607 -0.018637  
...           ...       ...       ...       ...       ...       ...       ...  
606     -0.280389 -0.279200 -0.280389 -0.279200 -0.279200 -0.279200 -0.269173  
607     -0.080237 -0.079430 -0.080237 -0.079430 -0.079430 -0.079430 -0.082687  
608     -0.246006 -0.246135 -0.246006 -0.246135 -0.246135 -0.246135 -0.233264  
609     -0.006131 -0.005824 -0.006131 -0.005824 -0.005824 -0.005824 -0.009527  
610     -0.229701 -0.234512 -0.229701 -0.234512 -0.234512 -0.234512 -0.184114  

[610 rows x 8983 columns]

In [57]:
# Initialize an empty list to store predictions
svd_predictions = []

# Iterate through the test data and make predictions
for _, row in test_data.iterrows():
    user_id = row['userId']
    movie_id = row['movieId']
    # Check if the user-movie pair exists in the SVD-reconstructed matrix
    if user_id in predicted_ratings_df.index and movie_id in predicted_ratings_df.columns:
        prediction = predicted_ratings_df.at[user_id, movie_id]
    else:
        # Handle missing predictions (e.g., assign the mean rating)
        prediction = train_data['rating'].mean()
    svd_predictions.append(prediction)

In [58]:
len(svd_predictions)

20168

In [59]:
svd_rmse = sqrt(mean_squared_error(test_data['rating'], svd_predictions))
print(f'SVD RMSE: {svd_rmse}')

SVD RMSE: 3.064533626329387


Task to do:
1. For SGD,  Lambda = 0.02 Gamma = 0.001 Epochs = 50, 100  K=3, Compute the initial and final RMSE with randomly initialized P and Q matrix. What is the effect of increasing the no. of epochs on RMSE?
2. For SGD,  Lambda = 0.02 Gamma = 0.001 Epochs = 100  K=5 and 10, Compute the initial and final RMSE with randomly initialized P and Q matrix. What is the effect of increasing the no. of latent fcators on RMSE?
3. For SGD,  Lambda = 0.05 Gamma = 0.001 Epochs = 50, 100  K=3, Compute the initial and final RMSE with randomly initialized P and Q matrix. What is the effect of increasing the lambda on RMSE?

Repeat the same for Batch gradient, which optimizer is better for optimizing RMSE and why?

Add user bias and item bias to the same and comment on effect on overall RMSE after adding bias to it.

Can we say that "Adding bias terms to user and item matrices in matrix factorization can potentially lead to a reduction in RMSE by allowing the model to capture systematic biases in the data"

# **STOCHASTIC GRADIENT DESCENT**

## TASK 1:
### Lambda = 0.02, Gamma= 0.001, Epochs= 50 and 100, K=3

#### Effect of Epochs on RMSE with SGD

In [62]:
# Parameters

lam = 0.02
gam = 0.001
epochs_50 = 50
epochs_100 = 100
K = 3 #latent factors

In [63]:
# P and Q matrices random init
P = np.random.rand(M, K)
Q = np.random.rand(K, N)

In [64]:
def sgd_factorization(R, P, Q, K, epochs, gamma, lambda_):
    initial_rmse = np.sqrt(error(R, P, Q) / len(R.data))
    print(f'Initial RMSE for {epochs} epochs: {initial_rmse}')

    for epoch in range(epochs):
        for ui in range(len(R.data)):
            rui = R.data[ui]
            u = R.row[ui]
            i = R.col[ui]
            if rui > 0:
                eui = rui - np.dot(P[u, :], Q[:, i])
                # Update P and Q
                P[u, :] += gamma * (eui * Q[:, i] - lambda_ * P[u, :])
                Q[:, i] += gamma * (eui * P[u, :] - lambda_ * Q[:, i])

    final_rmse = np.sqrt(error(R, P, Q) / len(R.data))
    print(f'Final RMSE for {epochs} epochs: {final_rmse}')
    return initial_rmse, final_rmse

In [68]:
# 50 Epochs
rmse_50 = sgd_factorization(R, np.copy(P), np.copy(Q), K, epochs_50, gam, lam)

Initial RMSE for 50 epochs: 2.9622918934352587
Final RMSE for 50 epochs: 0.9369707419618892


In [66]:
# 100 Epochs
rmse_100 = sgd_factorization(R, np.copy(P), np.copy(Q), K, epochs_100, gam, lam)

Initial RMSE for 100 epochs: 2.9622918934352587
Final RMSE for 100 epochs: 0.9001344843335589


## TASK 2:
### Lambda = 0.02, Gamma= 0.001, Epochs= 100, K=5 and 10

#### Effect of No of Latent Factors K on RMSE with SGD

In [69]:
K_values = [5, 10]
epochs = 100

for K in K_values:
    # Initialize P and Q matrices randomly for each value of K
    P = np.random.rand(M, K)
    Q = np.random.rand(K, N)
    print(f'\nRunning SGD with K={K} and {epochs} epochs')
    sgd_factorization(R, np.copy(P), np.copy(Q), K, epochs, gam, lam)


Running SGD with K=5 and 100 epochs
Initial RMSE for 100 epochs: 2.567172472601697
Final RMSE for 100 epochs: 0.8844427045699438

Running SGD with K=10 and 100 epochs
Initial RMSE for 100 epochs: 1.6560658721491417
Final RMSE for 100 epochs: 0.86643905396896


## TASK 3:
### Lambda = 0.05, Gamma= 0.001, Epochs= 100, K=3

#### Effect of No of Latent Factors K on RMSE with SGD

In [71]:
lambda_values = [0.05]
epochs_list = [50, 100]

for lambda_ in lambda_values:
    for epochs in epochs_list:
        # Initialize P and Q matrices randomly
        P = np.random.rand(M, K)
        Q = np.random.rand(K, N)
        print(f'\nRunning SGD with lambda={lambda_}, epochs={epochs}')
        sgd_factorization(R, np.copy(P), np.copy(Q), K, epochs, gam, lam)


Running SGD with lambda=0.05, epochs=50
Initial RMSE for 50 epochs: 1.6565672900056794
Final RMSE for 50 epochs: 0.903657865093359

Running SGD with lambda=0.05, epochs=100
Initial RMSE for 100 epochs: 1.6358357602855196
Final RMSE for 100 epochs: 0.867836861063577


# **BATCH GRADIENT DESCENT**

In [78]:
!pip install scipy
import numpy as np
from scipy.sparse import coo_matrix

def batch_factorization(R, P, Q, K, epochs, gamma, lambda_):
    initial_rmse = np.sqrt(error(R, P, Q) / len(R.data))
    print(f'Initial RMSE (Batch) for {epochs} epochs: {initial_rmse}')

    for epoch in range(epochs):
        # Iterate through the non-zero elements of R using R.row, R.col, R.data
        for u, i, rui in zip(R.row, R.col, R.data):
            if rui > 0:
                eui = rui - np.dot(P[u, :], Q[:, i])
                P[u, :] += gamma * (eui * Q[:, i] - lambda_ * P[u, :])
                Q[:, i] += gamma * (eui * P[u, :] - lambda_ * Q[:, i])

    final_rmse = np.sqrt(error(R, P, Q) / len(R.data))
    print(f'Final RMSE (Batch) for {epochs} epochs: {final_rmse}')
    return initial_rmse, final_rmse

## TASK 1:
### Lambda = 0.02, Gamma= 0.001, Epochs= 50 and 100, K=3

#### Effect of Epochs on RMSE with BGD

In [79]:
batch_factorization(R, np.copy(P), np.copy(Q), K=3, epochs=50, gamma=0.001, lambda_=0.02)

Initial RMSE (Batch) for 50 epochs: 1.6358357602855196
Final RMSE (Batch) for 50 epochs: 0.9056513231844288


(1.6358357602855196, 0.9056513231844288)

## TASK 2:
### Lambda = 0.02, Gamma= 0.001, Epochs= 100, K=5 and 10

#### Effect of No of Latent Factors K on RMSE with SGD

In [81]:
batch_factorization(R, np.copy(P), np.copy(Q), K=5, epochs=100, gamma=0.001, lambda_=0.02)

Initial RMSE (Batch) for 100 epochs: 1.6358357602855196
Final RMSE (Batch) for 100 epochs: 0.867836861063577


(1.6358357602855196, 0.867836861063577)

In [82]:
batch_factorization(R, np.copy(P), np.copy(Q), K=10, epochs=100, gamma=0.001, lambda_=0.02)

Initial RMSE (Batch) for 100 epochs: 1.6358357602855196
Final RMSE (Batch) for 100 epochs: 0.867836861063577


(1.6358357602855196, 0.867836861063577)

#CONCLUSION

**Effect of Increasing Epochs:** More epochs improve convergence, lowering RMSE until a threshold.

**Effect of Latent Factors (K):** Increasing K captures more detail, reducing RMSE up to a point before possibly overfitting.

**Effect of Lambda:** Larger lambda values may prevent overfitting but could also slow learning.

**Batch vs. SGD:** Batch tends to converge slower and may need more tuning in large datasets, while SGD is generally faster and better suited to sparse data.

**Adding Bias:** Bias terms generally reduce RMSE as they capture user/item-specific patterns that latent factors might miss.